version: '3.9'

services:
  db:
    image: mariadb:10.2
    ports:
      - 3333:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: maria
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    restart: always

volumes:
  db_data:
